# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170327_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='浏览器的 title 标签内容，用于搜索引擎优化。', max_length=255, null=True),
        ),
    ]
