# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20170422_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/categories/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'collection'), (2, 'tutorial')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='resource',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ongoing'), (2, 'finished')], null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
