# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 08:47
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170821_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modification time'),
        ),
    ]
