# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 06:40
from __future__ import unicode_literals

from django.db import migrations


def alter_posts_category(apps, schema_editor):
    Category = apps.get_model('blog', 'category')

    basic = Category.objects.get(slug='django-blog-tutorial')
    advanced = Category.objects.get(slug='django-advanced-blog-tutorial')
    posts = advanced.post_set.all()
    posts.update(category_id=basic.id)


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_auto_20170821_1647'),
    ]

    operations = [
        migrations.RunPython(alter_posts_category, migrations.RunPython.noop)
    ]
