# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 07:53
from __future__ import unicode_literals

import re

from django.db import migrations


def alter_body(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    posts = Post.objects.all()

    possibles = [
        r"- 加入 Django 学习小组 QQ 群：645793268。\r*\n*",
        r"- 加入 Django 学习小组 QQ 群：561422498。\r*\n*",
        r"- 将问题的详细描述发布到 \[Python 中文社区\].*?\r\n",
        r"- 加入 Django 学习小组 QQ 群，扫描下方二维码加入.*",
        r"- 加入 \[Pythonzhcn 社区\].*?\r\n"
    ]
    pattern = r'|'.join(possibles)
    repl = "- 在 [Pythonzhcn 社区的新手问答版块](http://www.pythonzh.cn/category/newbie-qa/) 发布帖子。\r\n"

    def f(matchobj):
        if matchobj.group(0) == "- 加入 [Pythonzhcn 社区](http://www.pythonzh.cn)。\r\n" \
                or matchobj.group(0) == "- 将问题的详细描述发布到 [Python 中文社区](http://www.pythonzh.cn/)，我会在 24 小时内为你解答。\r\n":
            return ''
        return repl

    for post in posts:
        post.body = re.sub(pattern, f, post.body, flags=re.DOTALL)
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_alter_posts_title'),
    ]

    operations = [
        migrations.RunPython(alter_body, migrations.RunPython.noop)
    ]
