# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 11:08
from __future__ import unicode_literals

from django.db import migrations
from django.utils.html import strip_tags

import markdown


def alter_meta(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    posts = Post.objects.all()

    for post in posts:
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        post.excerpt = strip_tags(md.convert(post.body))[:150]

        if not post.pub_date:
            post.pub_date = post.created_time

        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0013_alter_posts_body'),
    ]

    operations = [
        migrations.RunPython(alter_meta, migrations.RunPython.noop)
    ]
